---
title: "Flexdashboard with Shiny Widget"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(DT) # For DataTables
library(tigris)
library(leaflet)
library(sf)
library(shiny)
library(tidycensus)
```


```{r get data}

lang_pums <- get_pums(
  variables = c("PUMA", "LANP"),
  state = "TX",
  survey = "acs5",
  year = 2021,
  recode = TRUE)

summary(lang_pums)

```

```{r pumas}
tx_pumas <- pumas(state = "TX", cb = TRUE, year = 2020)
ggplot(tx_pumas) + 
  geom_sf() + 
  theme_void()
```


```{r}


# Function to load Texas PUMAs shapefile
load_pumas <- function() {
  pumas <- tigris::pumas("TX", year = 2020, cb = TRUE)
  pumas <- st_transform(pumas, crs = 4326)  # Transform to WGS84
  return(pumas)
}

# Load Texas PUMAs
pumas <- load_pumas()

# Create a shiny app
ui <- fluidPage(
  titlePanel("Texas PUMAs Explorer"),
  leafletOutput("map"),
  dataTableOutput("table")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      addPolygons(data = pumas, 
                  fillColor = "blue", 
                  fillOpacity = 0.5, 
                  color = "white", 
                  weight = 1,
                  layerId = ~GEOID20) %>%
      setView(lng = -99.5, lat = 31.5, zoom = 6)
  })
  
  output$table <- renderDataTable({
    event <- input$map_shape_click
    if (is.null(event))
      return(NULL)
    
    puma_id <- event$id
    puma_data <- pumas[pumas$GEOID20 == puma_id, ]
    
    # Here you can replace this with your data retrieval code based on the selected PUMA ID
    # For demonstration purposes, I'm just displaying the data associated with the selected PUMA
    puma_data <- data.frame(PUMA_ID = puma_id,
                            Area_Name = as.character(puma_data$NAME))
    return(puma_data)
  })
}

shinyApp(ui, server)

```

