---
title: "Data Validation Script for LanguageFinder"
author: Catherine Brockway, PhD; UN CIFAL Honolulu; catherine.lee.brockway@gmail.com;Epifania Petelo
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    theme: sandstone
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

This project seeks to make data about languages spoken in the US accessible to decision-makers in social sector enterprises. 

```{r env setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(kableExtra)
library(tigris)
options(tigris_use_cache = TRUE)
library(reactable)
# https://glin.github.io/reactable/articles/examples.html#basic-usage 
library(scales)
library(rmdformats)

options(reactable.theme = reactableTheme(
color = "hsl(100, 0%, 0%)",
backgroundColor = "hsl(0, 0%, 100%)",
borderColor = "hsl(233, 9%, 22%)",
stripedColor = "hsl(240, 3%, 94%)",
highlightColor = "hsl(95, 80%, 70%)",
inputStyle = list(backgroundColor = "hsl(0, 0%, 100%)"),
selectStyle = list(backgroundColor = "hsl(0, 0%, 100%)"),
pageButtonHoverStyle = list(backgroundColor = "hsl(0, 0%, 100%)"),
pageButtonActiveStyle = list(backgroundColor = "hsl(0, 0%, 100%)")
))
#set your census api key using instructions at https://walker-data.com/tidycensus/reference/census_api_key.html
Sys.getenv("CENSUS_API_KEY")
```

```{r get data, eval=FALSE, include=FALSE}
# This code chunk pulls the state level data using the Census API in the tidycensus package.
# https://walker-data.com/census-r/introduction-to-census-microdata.html
lang_pums <- get_pums(
  variables = c("LANP", "AGEP", "ENG"),
  state = "all",
  survey = "acs5",
  year = 2022,
  recode = TRUE
)

summary(lang_pums)

#This dataframe should include 15721123 obs of 11 variables.
```

```{r US totals}
# This applies the person weight function and gives total number of speakers for each language with all states combined.

#https://walker-data.com/census-r/introduction-to-census-microdata.html#understanding-default-data-from-get_pums
#https://walker-data.com/census-r/analyzing-census-microdata.html#basic-tabulation-of-weights-with-tidyverse-tools
us_totals <- lang_pums %>%
  count(LANP_label, wt = PWGTP)%>%
  arrange(desc(n))

# 129 obs of 2 variables.
```

```{r reactable US languages}
# Creates a table of language totals for the whole US.
reactable(
us_totals,
searchable = TRUE,
showPageSizeOptions = TRUE,
striped = TRUE,
highlight = TRUE,
columns = list(
LANP_label = colDef(name = "Language"),
n = colDef(name = "Number of Speakers")
)
)

#First row should have blank for language and 263034420 for number of speakers (these are the people who speak English at home). Spanish should have 41472790, Thai should have 169461, Other Bantu languages should have 80265.
```

```{r remove english data, eval=FALSE, include=FALSE}
nonEng <- lang_pums %>%
  filter(LANP != "000N")%>%
  select(PWGTP, AGEP, ST_label, ENG_label, LANP_label)
#write.csv(lang_nonEng, "NonEnglishLanguages2022.csv")

#2765093 obs of 5 variables
# just a note here, we may want to create a table that includes English speakers to get population totals at some point
```

```{r data cleaning}

# Convert categorical variables to factors and set order of levels in ENG
nonEng$ST_label <- as.factor(nonEng$ST_label)
nonEng$ENG_label <- as.factor(nonEng$ENG_label)
nonEng$ENG_label <- factor(nonEng$ENG_label, levels = c('Not at all', 'Not well', 'Well', 'Very well'))
nonEng$LANP_label <- as.factor(nonEng$LANP_label)

#Create categorical age groups using numerical AGEP
nonEng <- within(nonEng, {   
  AgeGroup <- NA # initialize categorical variable
  AgeGroup[AGEP < 18] <- "Youth"
  AgeGroup[AGEP >= 18 & AGEP < 65] <- "Adult"
  AgeGroup[AGEP >= 65] <- "Senior"
   } )

# Convert new AgeGroup variable to factor and set order of levels
nonEng$AgeGroup <- as.factor(nonEng$AgeGroup)
nonEng$AgeGroup <- factor(nonEng$AgeGroup, levels = c('Youth', 'Adult', 'Senior'))

# 2765093 obs of 6 variables
```


```{r include=FALSE}
# Create counts of all variable combinations using person weight (PWGTP)
lang_totals <- nonEng %>%
  count(LANP_label, ENG_label, AgeGroup, ST_label, wt = PWGTP)%>%
  arrange(desc(n))
# next line of code was used to create .csv that was loaded into bubble.io (beta version of LanguageFinder); no need to validate this
#write_csv(lang_totals, "LangAppData.csv")

# 30924 obs of 5 variables
```

```{r reactable all languages}
reactable(
lang_totals,
groupBy = c("LANP_label", "ST_label", "AgeGroup"),
searchable = TRUE,
showPageSizeOptions = TRUE,
striped = TRUE,
highlight = TRUE,
fullWidth = FALSE,
columns = list(
LANP_label = colDef(name = "Language", filterable = TRUE),
ENG_label = colDef(name = "Ability to Speak English", filterable = TRUE),
AgeGroup = colDef(name = "Age Group", filterable = TRUE),
ST_label = colDef(name = "State", filterable = TRUE),
n = colDef(name = "Number of Speakers", aggregate = "sum")
)
)
```