---
title: "Get Data on Languages Spoken in the US"
author: Catherine Brockway, PhD; UN CIFAL Honolulu; catherine.lee.brockway@gmail.com;Epifania Petelo
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    theme: sandstone
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

This project seeks to make data about languages spoken in the US accessible to decision-makers in social sector enterprises. 

```{r env setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(kableExtra)
library(tigris)
options(tigris_use_cache = TRUE)
library(reactable)
#set your census api key using instructions at https://walker-data.com/tidycensus/reference/census_api_key.html
Sys.getenv("CENSUS_API_KEY")
```

```{r get data, eval=FALSE, include=FALSE}
# This code chunk pulls the state level data using the Census API in the tidycensus package.

lang_pums <- get_pums(
  variables = c("LANP", "AGEP", "ENG"),
  state = "all",
  survey = "acs5",
  year = 2022,
  recode = TRUE
)

summary(lang_pums)

#This dataframe should include 15721123 obs of 11 variables.
```

```{r US totals}
# This applies the person weight function and gives total number of speakers for each language with all states combined.
us_totals <- lang_pums %>%
  count(LANP_label, wt = PWGTP)%>%
  arrange(desc(n))

# 129 obs of 2 variables.
```

```{r reactable US languages}
# Creates a table of language totals for the whole US.
reactable(
us_totals,
searchable = TRUE,
showPageSizeOptions = TRUE,
striped = TRUE,
highlight = TRUE,
columns = list(
LANP_label = colDef(name = "Language"),
n = colDef(name = "Number of Speakers")
)
)

#First row should have blank for language and 263034420 for number of speakers (these are the people who speak English at home). Spanish should have 41472790, Thai should have 169461, Other Bantu languages should have 80265.
```

```{r remove english data, eval=FALSE, include=FALSE}
lang_nonEng <- lang_pums %>%
  filter(LANP != "000N")%>%
  select(PWGTP, AGEP, ST_label, ENG_label, LANP_label)
#write.csv(lang_nonEng, "NonEnglishLanguages2022.csv")

```


```{r get hawaii data, eval=FALSE, include=FALSE}
lang_puma_hawaii <- get_pums(
  variables = c("PUMA", "LANP", "AGEP", "ENG"),
  state = "HI",
  survey = "acs5",
  year = 2021,
  recode = TRUE
)

summary(lang_puma_hawaii$PUMA)
```

```{r}
totals_HI_puma <- lang_puma_hawaii %>%
  count(PUMA, LANP_label, wt = PWGTP)%>%
  arrange(desc(n))
```

```{r subset HI data, eval=FALSE, include=FALSE}
lang_nonEng_HI <- lang_puma_hawaii %>%
  filter(LANP != "000N")%>%
  select(PWGTP, AGEP, PUMA, ENG_label, LANP_label)
write.csv(lang_nonEng_HI, "NonEnglishLanguagesHI.csv")

```

```{r}
hi_pumas <- map("HI", tigris::pumas, class = "sf", cb = TRUE, year = 2020) %>% 
  reduce(rbind)
```

```{r}
hi_map <- lang_puma_hawaii %>%
  group_by(PUMA) %>%
  summarize(
    total_pop = sum(PWGTP),
    pct_non_eng = sum(PWGTP[LANP != "000N"]) / total_pop
  )
```

```{r}

# zoom map: https://www.r-bloggers.com/2019/04/zooming-in-on-maps-with-sf-and-ggplot2/

hi_pumas %>%
  left_join(hi_map, by = c('PUMACE20' = 'PUMA')) %>%
  ggplot(aes(fill = pct_non_eng)) +
  geom_sf() +
  scale_fill_viridis_b(
    name = NULL,
    option = "magma",
    labels = scales::label_percent(1)
    ) +
  coord_sf(xlim = c(-153, -160), ylim = c(18.5, 23), expand = FALSE) +
  labs(title = "Percentage of population speaking a language other than English at home") +
   #geom_sf_text_repel(aes(label = PUMACE20)) +
    ggrepel::geom_text_repel(
    #data = PUMACE20,
    aes(label = NAMELSAD20, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0,
    colour = "darkgray",
    max.overlaps = 20
  )+
  theme_void()
```


```{r get texas data, eval=FALSE, include=FALSE}
lang_puma_texas <- get_pums(
  variables = c("PUMA", "LANP", "AGEP", "ENG"),
  state = "TX",
  survey = "acs5",
  year = 2021,
  recode = TRUE
)

summary(lang_puma_texas$PUMA)
```

```{r}
totals_TX_puma <- lang_puma_texas %>%
  count(PUMA, LANP_label, wt = PWGTP)%>%
  arrange(desc(n))
```

```{r subset TX data, eval=FALSE, include=FALSE}
lang_nonEng_TX <- lang_puma_texas %>%
  filter(LANP != "000N")%>%
  select(PWGTP, AGEP, PUMA, ENG_label, LANP_label)
write.csv(lang_nonEng_TX, "NonEnglishLanguagesTX.csv")

```

```{r}
tx_pumas <- map("TX", tigris::pumas, class = "sf", cb = TRUE, year = 2020) %>% 
  reduce(rbind)
```

```{r}
tx_map <- lang_puma_texas %>%
  group_by(PUMA) %>%
  summarize(
    total_pop = sum(PWGTP),
    pct_in_pov = sum(PWGTP[LANP != "000N"]) / total_pop
  )
```

```{r}
tx_pumas %>%
  left_join(tx_map, by = c('PUMACE20' = 'PUMA')) %>%
  ggplot(aes(fill = pct_in_pov)) +
  geom_sf() +
  scale_fill_viridis_b(
    name = NULL,
    option = "magma",
    labels = scales::label_percent(1)
    ) +
  #coord_sf(xlim = c(-153, -160), ylim = c(18.5, 23), expand = FALSE) +
  labs(title = "Percentage of population speaking a language other than English at home") +
   #geom_sf_text_repel(aes(label = PUMACE20)) +
    ggrepel::geom_text_repel(
    #data = PUMACE20,
    aes(label = NAMELSAD20, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0,
    colour = "darkgray",
    max.overlaps = 100
  )+
  theme_void()
```


```{r get data county, eval=FALSE, include=FALSE}
lang_county <- get_acs(
  variables = c("LANP", "AGEP", "ENG"),
  geography = "county",
  state = "TX",
  survey = "acs5",
  year = 2022,
  recode = TRUE
)

summary(lang_county)
```